[package]
name = "ninjoonline/library"
description = "Variety of different utility functions"
version = "1.3.7"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
